# Copyright © 2023 Zakhidov Dmitry <zakhidov.dim@yandex.ru>
# 
# This file may be used under the terms of the GNU General Public License
# version 3.0 as published by the Free Software Foundation and appearing in
# the file LICENSE included in the packaging of this file. Please review the
# following information to ensure the GNU General Public License version 3.0
# requirements will be met: https://www.gnu.org/copyleft/gpl.html.
# 
# This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
# WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

import logging
import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from PyQt5 import QtCore, QtGui, QtWidgets

logger = logging.getLogger(__name__)


class SVPS32_class:
    def __init__(self) -> None:
        pass


class Ui_SVPS34_control(object):
    def setupUi(self, SVPS34_control):
        SVPS34_control.setObjectName("SVPS34_control")
        SVPS34_control.resize(534, 431)
        self.centralwidget = QtWidgets.QWidget(SVPS34_control)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 410, 931, 211))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(20, 10, 171, 161))
        self.frame.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 126, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scan_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.scan_button.setMouseTracking(False)
        self.scan_button.setObjectName("scan_button")
        self.verticalLayout_2.addWidget(self.scan_button)
        self.comportslist = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comportslist.setObjectName("comportslist")
        self.verticalLayout_2.addWidget(self.comportslist)
        self.comportslist_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comportslist_2.setObjectName("comportslist_2")
        self.verticalLayout_2.addWidget(self.comportslist_2)
        self.connect_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.connect_button.setMouseTracking(False)
        self.connect_button.setObjectName("connect_button")
        self.verticalLayout_2.addWidget(self.connect_button)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 175, 881, 31))
        self.label_2.setStyleSheet("background-color: rgb(255, 194, 194);")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 20, 701, 151))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(200, 0, 511, 16))
        self.label.setObjectName("label")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(20, 30, 281, 121))
        self.lcdNumber.setObjectName("lcdNumber")
        self.common_button = QtWidgets.QPushButton(self.centralwidget)
        self.common_button.setGeometry(QtCore.QRect(20, 270, 81, 41))
        self.common_button.setMouseTracking(False)
        self.common_button.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.common_button.setObjectName("common_button")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(150, 260, 751, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ch1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ch1.setMouseTracking(False)
        self.ch1.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.ch1.setObjectName("ch1")
        self.horizontalLayout.addWidget(self.ch1)
        self.ch2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ch2.setMouseTracking(False)
        self.ch2.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.ch2.setObjectName("ch2")
        self.horizontalLayout.addWidget(self.ch2)
        self.ch3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ch3.setMouseTracking(False)
        self.ch3.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.ch3.setObjectName("ch3")
        self.horizontalLayout.addWidget(self.ch3)
        self.ch4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ch4.setMouseTracking(False)
        self.ch4.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.ch4.setObjectName("ch4")
        self.horizontalLayout.addWidget(self.ch4)
        self.ch5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ch5.setMouseTracking(False)
        self.ch5.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.ch5.setObjectName("ch5")
        self.horizontalLayout.addWidget(self.ch5)
        self.ch6 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ch6.setMouseTracking(False)
        self.ch6.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.ch6.setObjectName("ch6")
        self.horizontalLayout.addWidget(self.ch6)
        self.ch7 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ch7.setMouseTracking(False)
        self.ch7.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.ch7.setObjectName("ch7")
        self.horizontalLayout.addWidget(self.ch7)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(150, 320, 751, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rel1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.rel1.setMouseTracking(False)
        self.rel1.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.rel1.setObjectName("rel1")
        self.horizontalLayout_2.addWidget(self.rel1)
        self.rel2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.rel2.setMouseTracking(False)
        self.rel2.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.rel2.setObjectName("rel2")
        self.horizontalLayout_2.addWidget(self.rel2)
        self.rel3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.rel3.setMouseTracking(False)
        self.rel3.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.rel3.setObjectName("rel3")
        self.horizontalLayout_2.addWidget(self.rel3)
        self.rel4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.rel4.setMouseTracking(False)
        self.rel4.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.rel4.setObjectName("rel4")
        self.horizontalLayout_2.addWidget(self.rel4)
        self.rel5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.rel5.setMouseTracking(False)
        self.rel5.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.rel5.setObjectName("rel5")
        self.horizontalLayout_2.addWidget(self.rel5)
        self.rel6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.rel6.setMouseTracking(False)
        self.rel6.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.rel6.setObjectName("rel6")
        self.horizontalLayout_2.addWidget(self.rel6)
        self.rel7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.rel7.setMouseTracking(False)
        self.rel7.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.rel7.setObjectName("rel7")
        self.horizontalLayout_2.addWidget(self.rel7)
        self.common_rel_button = QtWidgets.QPushButton(self.centralwidget)
        self.common_rel_button.setGeometry(QtCore.QRect(20, 320, 81, 41))
        self.common_rel_button.setMouseTracking(False)
        self.common_rel_button.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.common_rel_button.setObjectName("common_rel_button")
        self.remote_button = QtWidgets.QPushButton(self.centralwidget)
        self.remote_button.setGeometry(QtCore.QRect(300, 50, 81, 41))
        self.remote_button.setMouseTracking(False)
        self.remote_button.setStyleSheet("background-color: rgb(255, 128, 141);")
        self.remote_button.setObjectName("remote_button")
        self.get_temp_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_temp_button.setGeometry(QtCore.QRect(750, 10, 101, 51))
        self.get_temp_button.setMouseTracking(False)
        self.get_temp_button.setStyleSheet("background-color: rgb(81, 244, 244);")
        self.get_temp_button.setObjectName("get_temp_button")
        self.temp_label = QtWidgets.QLabel(self.centralwidget)
        self.temp_label.setGeometry(QtCore.QRect(700, 70, 201, 41))
        self.temp_label.setStyleSheet('font: 75 14pt "MS Shell Dlg 2";')
        self.temp_label.setObjectName("temp_label")
        SVPS34_control.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SVPS34_control)
        self.statusbar.setObjectName("statusbar")
        SVPS34_control.setStatusBar(self.statusbar)

        self.retranslateUi(SVPS34_control)
        QtCore.QMetaObject.connectSlotsByName(SVPS34_control)

    def retranslateUi(self, SVPS34_control):
        _translate = QtCore.QCoreApplication.translate
        SVPS34_control.setWindowTitle(_translate("SVPS34_control", "SVPS34"))
        self.scan_button.setText(_translate("SVPS34_control", "Scan"))
        self.connect_button.setText(_translate("SVPS34_control", "Connect"))
        self.label_2.setText(_translate("SVPS34_control", "Нет подключенных портов"))
        self.label.setText(_translate("SVPS34_control", "Журнал"))
        self.common_button.setText(_translate("SVPS34_control", "Common"))
        self.ch1.setText(_translate("SVPS34_control", "+3.3V"))
        self.ch2.setText(_translate("SVPS34_control", "+5V"))
        self.ch3.setText(_translate("SVPS34_control", "+12V"))
        self.ch4.setText(_translate("SVPS34_control", "Ch4"))
        self.ch5.setText(_translate("SVPS34_control", "Ch5"))
        self.ch6.setText(_translate("SVPS34_control", "Ch6"))
        self.ch7.setText(_translate("SVPS34_control", "Ch7"))
        self.rel1.setText(_translate("SVPS34_control", "Rel"))
        self.rel2.setText(_translate("SVPS34_control", "Rel"))
        self.rel3.setText(_translate("SVPS34_control", "Rel"))
        self.rel4.setText(_translate("SVPS34_control", "Rel"))
        self.rel5.setText(_translate("SVPS34_control", "Rel"))
        self.rel6.setText(_translate("SVPS34_control", "Rel"))
        self.rel7.setText(_translate("SVPS34_control", "Rel"))
        self.common_rel_button.setText(_translate("SVPS34_control", "Common Rel"))
        self.remote_button.setText(_translate("SVPS34_control", "Remote"))
        self.get_temp_button.setText(_translate("SVPS34_control", "Get temperature"))
        self.temp_label.setText(_translate("SVPS34_control", "Temperature = "))
