# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'installationofdevices.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import logging
logger = logging.getLogger(__name__)

class installation_Ui_Dialog(QtWidgets.QDialog):
    signal_to_main_window = QtCore.pyqtSignal(list)

    def setupUi(self, Dialog, mother_window):
        self.signal_to_main_window.connect(
            mother_window.message_from_new_installation)
        Dialog.setObjectName("Dialog")
        Dialog.resize(330, 243)
        Dialog.setSizeGripEnabled(True)
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        
        self.label = QtWidgets.QLabel("Выберите приборы для установки")
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.verticalLayout_2.addWidget(self.label)
        
        self.splitter = QtWidgets.QSplitter(QtCore.Qt.Horizontal)
        self.verticalLayout_2.addWidget(self.splitter)
        
        self.widget1 = QtWidgets.QWidget()
        self.widget1_layout = QtWidgets.QVBoxLayout(self.widget1)
        self.widget1_layout.setContentsMargins(0, 0, 0, 0)
        
        font = QtGui.QFont()
        font.setPointSize(12)

        self.checkBox = QtWidgets.QCheckBox("Maisheng WSD-20H15")
        self.checkBox.setFont(font)
        self.widget1_layout.addWidget(self.checkBox)

        self.checkBox_2 = QtWidgets.QCheckBox("АКИП-2404")
        self.checkBox_2.setFont(font)
        self.widget1_layout.addWidget(self.checkBox_2)

        self.checkBox_3 = QtWidgets.QCheckBox("Polarity Relay")
        self.checkBox_3.setFont(font)
        self.widget1_layout.addWidget(self.checkBox_3)

        self.checkBox_4 = QtWidgets.QCheckBox("SR830")
        self.checkBox_4.setFont(font)
        self.widget1_layout.addWidget(self.checkBox_4)

        self.checkBox_5 = QtWidgets.QCheckBox("Rigol DP832A")
        self.checkBox_5.setFont(font)
        self.widget1_layout.addWidget(self.checkBox_5)

        self.checkBox_6 = QtWidgets.QCheckBox("E7-20MNIPI")
        self.checkBox_6.setFont(font)
        self.widget1_layout.addWidget(self.checkBox_6)

        self.splitter.addWidget(self.widget1)

        self.buttonBox = QtWidgets.QDialogButtonBox(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.verticalLayout_2.addWidget(self.buttonBox)
        
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).clicked.connect(self.send_signal)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Мастер создания установки"))

    def send_signal(self):
        device_list = []
        if self.checkBox.isChecked():
            device_list.append("Maisheng")
        if self.checkBox_2.isChecked():
            device_list.append("АКИП-2404")
        if self.checkBox_3.isChecked():
            device_list.append("PR")
        if self.checkBox_4.isChecked():
            device_list.append("SR830")
        if self.checkBox_5.isChecked():
            device_list.append("DP832A")
        if self.checkBox_6.isChecked():
            device_list.append("E7-20MNIPI")

        self.signal_to_main_window.emit(device_list)
