# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'installation_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Installation(QtWidgets.QMainWindow):
    installation_close_signal = QtCore.pyqtSignal(int)

    def setupUi(self, Installation, list_of_device):
        Installation.setObjectName("Installation")
        self.list_of_device = list_of_device
        self.N = len(list_of_device)
        if self.N < 3:
            self.N = 3
        Installation.resize(self.N*160+10+270, 510)
        self.centralwidget = QtWidgets.QWidget(Installation)
        self.centralwidget.setObjectName("centralwidget")
        # --------------------------
        i = 0
        self.verticalLayoutWidget = {}
        self.verticalLayout = {}
        self.horizontalLayout = {}
        self.name_device = {}
        self.number_device = {}
        self.label = {}
        self.change_device_button = {}
        for device in self.list_of_device:
            self.verticalLayoutWidget[device] = (
                QtWidgets.QWidget(self.centralwidget))
            self.verticalLayoutWidget[device].setGeometry(
                QtCore.QRect(25+(int((150*self.N)/len(self.list_of_device)))*i, 0, int((150*self.N)/len(self.list_of_device))-10, 320))
            self.verticalLayoutWidget[device].setObjectName(
                "verticalLayoutWidget" + str(i))
            self.verticalLayoutWidget[device].setStyleSheet(
                "background-color: rgb(255, 180, 180);")
            self.verticalLayout[device] = (
                QtWidgets.QVBoxLayout(self.verticalLayoutWidget[device]))
            self.verticalLayout[device].setContentsMargins(5, 0, 0, 0)
            self.verticalLayout[device].setObjectName(
                "verticalLayout" + str(i))
            self.horizontalLayout[device] = (QtWidgets.QHBoxLayout())
            self.horizontalLayout[device].setObjectName(
                "horizontalLayout_" + str(i))
            self.name_device[device] = (QtWidgets.QLabel(
                self.verticalLayoutWidget[device]))
            font = QtGui.QFont()
            font.setPointSize(11)
            font.setBold(True)
            font.setWeight(75)
            self.name_device[device].setFont(font)
            self.name_device[device].setLayoutDirection(QtCore.Qt.RightToLeft)
            self.name_device[device].setAlignment(QtCore.Qt.AlignCenter)
            self.name_device[device].setObjectName("name_device_" + device)
            self.number_device[device] = (
                QtWidgets.QLabel(self.verticalLayoutWidget[device]))
            self.number_device[device].setFont(font)
            self.number_device[device].setAlignment(QtCore.Qt.AlignCenter)
            self.number_device[device].setObjectName("number_device_"+str(i+1))
            self.horizontalLayout[device].addWidget(self.number_device[device])
            self.horizontalLayout[device].addWidget(self.name_device[device])
            self.verticalLayout[device].addLayout(
                self.horizontalLayout[device])
            self.label[device] = (QtWidgets.QLabel(
                self.verticalLayoutWidget[device]))
            self.label[device].setObjectName("label+" + str(i+1))
            self.verticalLayout[device].addWidget(self.label[device])
            self.change_device_button[device] = (QtWidgets.QPushButton(device))
            self.change_device_button[device].setObjectName(
                "change_device_button_" + str(i+1))
            self.verticalLayout[device].addWidget(
                self.change_device_button[device])
            i += 1

        self.pbar = QtWidgets.QProgressBar(self.centralwidget)
        self.pbar.setGeometry(QtCore.QRect(
            10, 440, 15+160*self.N, 20))
        self.pbar.setValue(0)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(
            30+160*self.N, 340, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.start_button.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.pause_button = QtWidgets.QPushButton(self.centralwidget)
        self.pause_button.setGeometry(QtCore.QRect(
            30+160*self.N, 440, 101, 23))
        self.pause_button.setObjectName("pause_button")
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(
            150+160*self.N, 440, 101, 23))
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(
            20+160*self.N, 0, 231, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_schematic = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_schematic.setObjectName("label_schematic")
        self.gridLayout.addWidget(self.label_schematic, 0, 0, 1, 1)
        self.schematic_installation = QtWidgets.QGraphicsView(
            self.gridLayoutWidget)
        self.schematic_installation.setObjectName("schematic_installation")
        self.gridLayout.addWidget(self.schematic_installation, 1, 0, 1, 1)

        # self.log = QtWidgets.QLineEdit(self.centralwidget)
        # self.log.setGeometry(QtCore.QRect(10, 320, 10+160*self.N, 110))
        # self.log.setObjectName("log_text")

        self.log = QtWidgets.QTextEdit(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(
            10, 320, 10+160*self.N, 110))
        self.log.setObjectName("log_text")
        self.log.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.log.setReadOnly(True)

        Installation.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Installation)
        self.menubar.setGeometry(QtCore.QRect(10, 0, 590, 20))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Installation.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Installation)
        self.statusbar.setObjectName("statusbar")
        Installation.setStatusBar(self.statusbar)
        self.save_installation_button = QtWidgets.QAction(Installation)
        self.save_installation_button.setObjectName("save_installation_button")
        self.open_installation_button = QtWidgets.QAction(Installation)
        self.open_installation_button.setObjectName("open_installation_button")
        self.add_device_button = QtWidgets.QAction(Installation)
        self.add_device_button.setObjectName("add_device_button")
        self.menu.addAction(self.save_installation_button)
        self.menu.addAction(self.open_installation_button)
        self.menu.addSeparator()
        self.menu.addAction(self.add_device_button)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Installation)
        QtCore.QMetaObject.connectSlotsByName(Installation)

    def closeEvent(self, event):  # эта функция вызывается при закрытии окна
        print("окно инталляции закрыто крестиком")
        self.installation_close_signal.emit(1)

    def retranslateUi(self, Installation):
        _translate = QtCore.QCoreApplication.translate
        Installation.setWindowTitle(_translate("Installation", "MainWindow"))
        i = 0
        for device in self.list_of_device:
            self.name_device[device].setText(
                _translate("Installation", device))
            self.number_device[device].setText(
                _translate("Installation", str(i+1)))
            self.label[device].setText(_translate(
                "Installation", "Не настроено"))
            self.change_device_button[device].setText(
                _translate("Installation", "Изменить настройки"))
            i += 1
        self.start_button.setText(_translate("Installation", "Запуск"))
        self.pause_button.setText(_translate("Installation", "Пауза"))
        self.cancel_button.setText(_translate("Installation", "Отмена"))
        self.label_schematic.setText(
            _translate("Installation", "Схема установки"))
        self.menu.setTitle(_translate("Installation", "Меню"))
        self.save_installation_button.setText(
            _translate("Installation", "Сохранить установку"))
        self.open_installation_button.setText(
            _translate("Installation", "Открыть установку"))
        self.add_device_button.setText(
            _translate("Installation", "Добавить прибор"))
