from PyQt5 import QtCore, QtGui, QtWidgets

		self.buttonBox = QtWidgets.QDialogButtonBox(Set_power_supply)
        self.buttonBox.setGeometry(QtCore.QRect(80, 340, 191, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.label_trig = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_trig.setObjectName("label_trig")
        self.triger_enter = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.triger_enter.setCurrentText("")
        self.triger_enter.setObjectName("triger_enter")
        self.second_value_limit_label = QtWidgets.QLabel(
            self.horizontalLayoutWidget33)
        self.second_value_limit_label.setObjectName("second_value_limit_label")

        self.second_limit_enter = QtWidgets.QComboBox(
            self.horizontalLayoutWidget33)
        self.second_limit_enter.setCurrentText("")
        self.second_limit_enter.setObjectName("second_limit_enter")
        self.second_limit_enter.setEditable(True)

        self.radioButton = QtWidgets.QRadioButton(
            self.horizontalLayoutWidget333)
        self.radioButton.setObjectName("radioButton")
        
        self.label_type_step = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_type_step.setObjectName("label_type_step")
        self.type_step_enter = QtWidgets.QComboBox(
            self.horizontalLayoutWidget_2)
        self.type_step_enter.setCurrentText("")
        self.type_step_enter.setObjectName("type_step_enter")
        self.label_mode_work = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_mode_work.setObjectName("label_mode_work")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.type_work_enter = QtWidgets.QComboBox(
            self.horizontalLayoutWidget_3)
        self.type_work_enter.setCurrentText("")
        self.type_work_enter.setObjectName("type_work_enter")

        self.label_step = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_step.setObjectName("label_step")
        self.label_end_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_end_value.setObjectName("label_end_value")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.start_enter = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.start_enter.setEditable(True)
        self.start_enter.setCurrentText("")
        self.start_enter.setObjectName("start_enter")
        self.stop_enter = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.stop_enter.setEditable(True)
        self.stop_enter.setCurrentText("")
        self.stop_enter.setObjectName("stop_enter")
        self.step_enter = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.step_enter.setStyleSheet("")
        self.step_enter.setEditable(True)
        self.step_enter.setCurrentText("")
        self.step_enter.setObjectName("step_enter")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")

        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.comportslist = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.comportslist.setObjectName("comportslist")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_11.setObjectName("label_11")
        self.boudrate = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.boudrate.setObjectName("boudrate")

        self.label_sourse = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_sourse.setObjectName("label_sourse")
        self.sourse_enter = QtWidgets.QComboBox(self.horizontalLayoutWidget_6)
        self.sourse_enter.setCurrentText("")
        self.sourse_enter.setObjectName("sourse_enter")